# Generated by Django 6.1.1 on 2026-10-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(db_index=True, max_length=255)),
                ('arguments', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('enqueued', 'Enqueued'), ('running', 'Running'), ('pausing', 'Pausing'), ('paused', 'Paused'), ('cancelling', 'Cancelling'), ('cancelled', 'Cancelled'), ('succeeded', 'Succeeded'), ('errored', 'Errored')], db_index=True, default='enqueued', max_length=16)),
                ('cursor', models.JSONField(blank=True, null=True)),
                ('tick_count', models.PositiveBigIntegerField(default=0)),
                ('tick_total', models.PositiveBigIntegerField(blank=True, null=True)),
                ('generation', models.PositiveIntegerField(default=0)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('error_class', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('backtrace', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['enqueued', 'running', 'pausing', 'paused', 'cancelling'])), fields=('task_name',), name='maintenance_tasks_one_active_run_per_task')],
            },
        ),
    ]
